/**
 * Generated by Midnight Compact Compiler v0.23.4
 * Contract: PrivateVote
 * Target: Midnight Preprod / Preview
 */

class PrivateVoteContract {
  constructor(witnesses, initialLedger = {}) {
    this.witnesses = witnesses;
    this.ledger = {
      proposalId: initialLedger.proposalId || null,
      status: initialLedger.status || 0,
      nullifiers: initialLedger.nullifiers || new Map(),
      tallyYes: initialLedger.tallyYes || 0,
      tallyNo: initialLedger.tallyNo || 0,
      tallyAbstain: initialLedger.tallyAbstain || 0,
    };
  }
}

module.exports = { PrivateVoteContract };
