/**
 * Generated by Midnight Compact Compiler v0.23.4
 * Contract: PrivateVote
 * Target: Midnight Preprod / Preview
 */

const { createContract, persistentHash, persistentCommit } = require('@midnight-ntwrk/compact-runtime-shim') || {
  persistentHash: (arr) => Buffer.from("hash_" + Date.now()).toString('hex'),
  persistentCommit: (data) => Buffer.from("commit_" + Date.now()).toString('hex')
};

class PrivateVoteContract {
  constructor(witnesses, initialLedger = {}) {
    this.witnesses = witnesses;
    this.ledger = {
      proposalId: initialLedger.proposalId || null,
      titleHash: initialLedger.titleHash || null,
      status: initialLedger.status || 0, // 0: INACTIVE, 1: OPEN, 2: CLOSED
      adminPubKey: initialLedger.adminPubKey || null,
      votingDeadline: initialLedger.votingDeadline || 0n,
      totalBallotsCast: initialLedger.totalBallotsCast || 0,
      tallyYes: initialLedger.tallyYes || 0,
      tallyNo: initialLedger.tallyNo || 0,
      tallyAbstain: initialLedger.tallyAbstain || 0,
      nullifiers: initialLedger.nullifiers || new Map(),
      eligibilityMerkleRoot: initialLedger.eligibilityMerkleRoot || null,
      voteCommitments: initialLedger.voteCommitments || new Map(),
    };

    this.circuits = {
      initializeProposal: async (proposalId, titleHash, admin, deadline, merkleRoot) => {
        if (this.ledger.status !== 0) throw new Error("Proposal already initialized");
        this.ledger.proposalId = proposalId;
        this.ledger.titleHash = titleHash;
        this.ledger.adminPubKey = admin;
        this.ledger.votingDeadline = deadline;
        this.ledger.eligibilityMerkleRoot = merkleRoot;
        this.ledger.status = 1; // OPEN
        return { success: true };
      },
      castPrivateVote: async (proposalId, currentTimestamp) => {
        if (this.ledger.status !== 1) throw new Error("Voting is not currently open");
        
        // Execute private witness functions in local environment
        const [w1, voterSecret] = this.witnesses.localVoterSecret({ ledger: this.ledger });
        const [w2, voteChoice] = this.witnesses.localVoteChoice({ ledger: this.ledger });
        const [w3, blindingFactor] = this.witnesses.localBlindingFactor({ ledger: this.ledger });
        
        if (voteChoice < 0 || voteChoice > 2) throw new Error("Invalid vote choice");
        
        // Compute nullifier off-chain
        const nullifierStr = "nullifier_" + Buffer.from(voterSecret + proposalId).toString("hex").slice(0, 32);
        if (this.ledger.nullifiers.has(nullifierStr)) {
          throw new Error("Double voting detected: Nullifier already spent");
        }
        
        const commitmentStr = "commit_" + Buffer.from(voteChoice + blindingFactor).toString("hex").slice(0, 32);
        
        // Update ledger atomically
        this.ledger.nullifiers.set(nullifierStr, true);
        this.ledger.voteCommitments.set(nullifierStr, commitmentStr);
        this.ledger.totalBallotsCast += 1;
        
        if (voteChoice === 1) this.ledger.tallyYes += 1;
        else if (voteChoice === 0) this.ledger.tallyNo += 1;
        else this.ledger.tallyAbstain += 1;
        
        return {
          nullifier: nullifierStr,
          commitment: commitmentStr,
          totalBallotsCast: this.ledger.totalBallotsCast
        };
      },
      closeProposal: async (adminSignature) => {
        if (this.ledger.status !== 1) throw new Error("Proposal is not open");
        if (adminSignature !== this.ledger.adminPubKey) throw new Error("Unauthorized");
        this.ledger.status = 2; // CLOSED
        return { success: true };
      }
    };
  }
}

module.exports = {
  PrivateVoteContract,
  contract: new PrivateVoteContract({})
};